"""Public exports for alphaxiv-py."""

from .assistant import AssistantAPI
from .auth import SavedAuth
from .client import AlphaXivClient
from .exceptions import AlphaXivError, APIError, AuthRequiredError, ResolutionError
from .types import (
    AssistantContext,
    AssistantMessage,
    AssistantRun,
    AssistantSession,
    AssistantStreamEvent,
    Author,
    Citation,
    ExploreFilterOptions,
    FeedCard,
    HomepageSearchResults,
    ImplementationResource,
    Mention,
    OrganizationResult,
    OverviewStatus,
    OverviewSummary,
    OverviewTranslationStatus,
    Paper,
    PaperFullText,
    PaperGroup,
    PaperMetrics,
    PaperOverview,
    PaperResources,
    PaperTextPage,
    PaperTranscript,
    PaperVersion,
    PodcastTranscriptLine,
    ResolvedPaper,
    SearchResult,
)

__all__ = [
    "APIError",
    "AlphaXivClient",
    "AlphaXivError",
    "AssistantAPI",
    "AssistantContext",
    "AssistantMessage",
    "AssistantRun",
    "AssistantSession",
    "AssistantStreamEvent",
    "AuthRequiredError",
    "Author",
    "Citation",
    "ExploreFilterOptions",
    "FeedCard",
    "HomepageSearchResults",
    "ImplementationResource",
    "Mention",
    "OrganizationResult",
    "OverviewStatus",
    "OverviewTranslationStatus",
    "OverviewSummary",
    "PaperFullText",
    "Paper",
    "PaperGroup",
    "PaperMetrics",
    "PaperOverview",
    "PaperResources",
    "PaperTranscript",
    "PaperTextPage",
    "PaperVersion",
    "PodcastTranscriptLine",
    "ResolutionError",
    "ResolvedPaper",
    "SavedAuth",
    "SearchResult",
]

__version__ = "0.1.0"
